### PR TITLE
Solving issue - Lists not being rendered #6

### PR DESCRIPTION
**Pull request by iamraf-ca**
Add <style> block at base.html to show the square for common lists `<li>` in all pages.
The other lists objects, like dropdown, tags, blogroll, etc, will not be affect because I don't made any change at skel.min.js.

### CODE REVIEW

**Comment by PierrePaul** [comment]
Any reason why it's not in the style.css file?

**Comment by iamraf-ca** [comment]
No, there's no reason, you are right, sorry about that.
I can transfer the code to style.css tomorrow morning, is 23:50h here in
Brazil now.

Thanks,

**Comment by PierrePaul** [comment]
No rush, take your time :) thanks

**Comment by iamraf-ca** [comment]
Closing this pull request to put the <style> block inside the style.css

**Pull request closed without merging**
